<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MessagePipe" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="R3" />
    <PackageReference Include="UnitGenerator" PrivateAssets="all" />
  </ItemGroup>

</Project>
